### ISSUE TITLE
Dim Display

### ISSUE THREAD

**Issue by Kernel-ROM** [wuspy/portal_calendar#4]
The display is working but dim.

I can see the screen is able to display black properly when it's starting up/refreshing, but then is faded when loaded.

Do you have any thoughts?

Also, thanks for the awesome project!

![firefox_2FyLJQNtYV](https://user-images.githubusercontent.com/1376110/211162318-91e6a993-cf62-4203-868e-dd414524fba3.png)

**Comment by wuspy** [comment]
This is pretty weird, I've read that trying to use 4-color grayscale with these displays can have mixed results but I've never seen anything like that. On the e-paper HAT, is the display config switch in the B position?

I just pushed a branch called stock_waveform_test that uses the default 2-color grayscale waveforms that the waveshare examples for this display uses, can you try that out and see if the blacks look better?

**Comment by Kernel-ROM** [comment]
Yup, in position B and the exact same hardware as yourself.

The latest changes look drastically better, but the blacks are still not as dark as my other waveshare displays and your own example images. It's useable now though!

I'm starting to think that my display or the HAT are faulty - will contact waveshare.

Thanks for the quick turnaround!

![firefox_zpS99LANEa](https://user-images.githubusercontent.com/1376110/211200296-284a90c9-6de9-42a4-8c88-808927a65fb9.png)

**Comment by wuspy** [comment]
I updated stock_waveform_test to revert the remaining settings I changed back to waveshare defaults, if you want you can try that again to see if it looks better. Hopefully it doesn't look better though, because then that would mean your display isn't technically 'faulty' and these displays just have way looser manufacturing tolerances than I thought.

I wish there was more I could do to help, I'm definitely not an expert on e-paper tech. One thing that can be done is adjusting the VCOM_DC level in DisplayGDEW075T7.cpp to tweak the contrast and grayscale levels, but that's more of a fine tuning thing and probably won't help for such an extreme case
```cpp
    sendCommand(CMD_VDCS);  // VCOM DC Setting (min 0x00 = -0.1v, max 0x4F = -4.05v)
    sendData(0x26);         // -2.0v
```

**Comment by Kernel-ROM** [comment]
Set it to `0x28` (and using the stock fork) and display looks much closer to the example images.

Many thanks!
